# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-29 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='loginuser',
            field=models.CharField(default=111, max_length=255, verbose_name='Login User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Server User'),
        ),
    ]
